In [ ]:
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])  # 1 维
print(x[0:1].dim())   # 1
print(x[0].dim())  # 0


1
0


In [ ]:
x = torch.tensor([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
]) # 2 维
#假如我们要取第一行，那么严格意义上说我们要取第一个维度的第一个元素，第二个维度的所有元素
#同上我们存在两种写法
print(x[:1 , :])
print(x[:1 , :].dim()) # 还是2维 
print(x[0 , :])  
print(x[0 , :].dim())  # 降维


tensor([[1, 2, 3, 4, 5, 6]])
2
tensor([1, 2, 3, 4, 5, 6])
1


In [9]:
x = torch.randn(2,3, 4, 5, 6)
print(x[0:1,:,:,:,:])


tensor([[[[[-0.8758, -0.0330,  0.4591,  1.7274, -0.0801,  0.3367],
           [ 0.0132, -1.4742, -1.5733, -1.6462,  0.0602, -1.1284],
           [-0.0548,  0.2007, -1.5016, -0.2568,  1.0229, -1.0942],
           [ 0.5076, -0.9172,  0.0200, -0.3135, -2.6007, -0.1699],
           [-0.0414,  0.3871, -0.6292, -0.4175, -1.4331,  0.4696]],

          [[-0.9451, -0.3536, -1.0962, -1.2529, -0.2121,  0.7179],
           [-0.0333, -1.2162, -0.5936,  0.7980, -0.4550,  0.3748],
           [-0.9483, -0.9953, -0.6747, -0.6834,  0.4496,  0.8538],
           [ 1.3360, -0.9037,  0.8422,  0.6086, -1.5040,  0.7065],
           [-0.2368,  0.1743, -0.2146, -0.6853, -0.6219,  0.6852]],

          [[ 0.3404, -0.7130,  1.0924, -1.4955,  1.6064,  0.4455],
           [-1.3447,  0.1217,  0.7485,  0.1977, -2.0243,  1.5217],
           [ 0.2505, -1.6050, -2.6574, -1.2049, -0.1853,  1.0576],
           [ 0.8850, -2.0185, -0.9556,  1.3014, -0.5369, -0.0682],
           [-0.7911, -0.5173, -0.6523,  2.4652,  0.1481,  

In [ ]:
x = torch.tensor(
[[1, 2, 3, 4, 5, 6, 7, 8],
 [9,10,11,12,13,14,15,16]])
y = x[...,:4]
print("y:", y)
z = x[...,4:]
print("z:", z)

y: tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]])
z: tensor([[ 5,  6,  7,  8],
        [13, 14, 15, 16]])
