In [35]:
import cv2   #opencv读取的格式是BGR
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline







In [36]:

def cv_show(name,img):
    cv2.imshow('pig',img)  #image弹出的图片展示窗口名称，img为对象名
    cv2.waitKey(0)   #按任意键退出
    cv2.destroyAllWindows()

In [37]:
img=cv2.imread('pig.jpg')

pig=img[50:200,200:400]  #前一个区域代表纵区域，后面的代表横区域

#cv_show('eye',pig)

颜色通道提取

In [38]:
b,g,r=cv2.split(img)

In [39]:
b

array([[246, 246, 246, ..., 247, 247, 247],
       [246, 246, 246, ..., 247, 247, 247],
       [246, 246, 246, ..., 247, 247, 247],
       ...,
       [198, 198, 198, ..., 122, 122, 122],
       [169, 169, 169, ..., 122, 122, 122],
       [151, 151, 151, ..., 118, 118, 118]], shape=(672, 632), dtype=uint8)

In [40]:
g

array([[195, 195, 195, ..., 195, 195, 195],
       [195, 195, 195, ..., 195, 195, 195],
       [195, 195, 195, ..., 195, 195, 195],
       ...,
       [199, 199, 199, ..., 207, 207, 207],
       [202, 202, 202, ..., 207, 207, 207],
       [205, 205, 205, ..., 208, 208, 208]], shape=(672, 632), dtype=uint8)

In [41]:
r

array([[152, 152, 152, ..., 154, 154, 154],
       [152, 152, 152, ..., 154, 154, 154],
       [152, 152, 152, ..., 154, 154, 154],
       ...,
       [143, 143, 143, ..., 133, 133, 133],
       [141, 141, 141, ..., 132, 132, 132],
       [140, 140, 140, ..., 132, 132, 132]], shape=(672, 632), dtype=uint8)

In [42]:
#只保留R
cur_img=img.copy()
cur_img[:,:,0]=0 #所有像素点的b通道为0
cur_img[:,:,1]=0 #所有像素点的g通道为0
cv_show('R',cur_img)

In [43]:
#只保留G
cur_img=img.copy()
cur_img[:,:,0]=0 #所有像素点的b通道为0
cur_img[:,:,2]=0 #所有像素点的g通道为0
cv_show('G',cur_img)

In [44]:
#只保留B
cur_img=img.copy()
cur_img[:,:,1]=0 #所有像素点的b通道为0
cur_img[:,:,2]=0 #所有像素点的g通道为0
cv_show('B',cur_img)

In [45]:
img=cv2.merge([b,g,r])
cv_show('again-img',img)