# Numpy入门

## 第一章：数组的属性

In [13]:
import numpy as np

a = np.array([[3,4,6], [1,2,3]])

print("\n数组本身:\n",a)
print("\n数组的形状:",a.shape)
print("\n数组的元素类型:",a.dtype)
print("\n数组的维度:",a.ndim)
print("\n数组的元素数量:",a.size)
print("\n数组的单个元素内存占用:",a.itemsize)
print("\n数组的总内存占用:",a.nbytes)
print("\n数组的转置矩阵:\n",a.T)



数组本身:
 [[3 4 6]
 [1 2 3]]

数组的形状: (2, 3)

数组的元素类型: int64

数组的维度: 2

数组的元素数量: 6

数组的单个元素内存占用: 8

数组的总内存占用: 48

数组的转置矩阵:
 [[3 1]
 [4 2]
 [6 3]]


## 第二章：数组的创建

In [ ]:
import numpy as np

# 从列表中创建
list = [[3,4,6],[1,2,3]]
a = np.array(list, dtype=np.float32) # 指定元素类型为float32
print("\n从列表创建的数组a本身:\n",a)

# copy 其他数组
a_copy = a.copy() # 深拷贝。如果直接a_copy=a的话，修改a_copy也会修改a_copy
print("\n使用copy方法创建的数组a_copy:\n",a_copy)

# 预定义形状
arr = np.zeros((2,3)) # 2行3列的0矩阵
print("\n预定义形状的数组arr:\n",arr)



从列表创建的数组a本身:
 [[3. 4. 6.]
 [1. 2. 3.]]

使用copy方法创建的数组a_copy:
 [[3. 4. 6.]
 [1. 2. 3.]]

预定义形状的数组arr:
 [[0. 0. 0.]
 [0. 0. 0.]]


## 第三章：线性代数

### 3-1 线性代数的运算

In [15]:
# numpy.dot()
## 对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为向量点积)；
## 对于二维数组，计算的是两个数组的矩阵乘积；
arr1=[1,2,3]
arr2=[4,5,6]
arr_dot=np.dot(arr1,arr2) #矩阵点乘（向量内积）
print("\n向量点积:\n",arr_dot)

A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
arr_dot=np.dot(A,B)   #矩阵乘法（向量内积）
print("\n矩阵乘积:\n",arr_dot)


向量点积:
 32

矩阵乘积:
 [[ 7 10]
 [15 22]]


### 3-2 linalg（线性代数）工具包
- solve（求线性方程组）
- inv（逆矩阵）
- eig（特征值和特征向量）
- det（行列式）

In [16]:
# 解方程
# 若A*X=B，则X可以通过 np.linalg.solve(A,B) 求解
A=np.array([[1,1,1],
            [0,2,5],
            [2,5,-1]])
B=np.array([6,-4,27])
print(np.linalg.solve(A,B))

[ 5.  3. -2.]


In [17]:
# 求逆矩阵
print(np.linalg.inv(A)) #求逆矩阵
print(np.dot(np.linalg.inv(A),A)) #验证逆矩阵的性质，应该相乘为单位矩阵

[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
[[ 1.00000000e+00 -2.77555756e-16 -6.10622664e-16]
 [ 0.00000000e+00  1.00000000e+00  2.77555756e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [18]:
# 定义矩阵
A = np.array([[-1, 1, 0],
[-4, 3, 0],
[1, 0, 2]])

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(A)

print("特征值:", eigenvalues)
print("特征向量:\n", eigenvectors)

特征值: [2. 1. 1.]
特征向量:
 [[ 0.          0.40824829  0.40824829]
 [ 0.          0.81649658  0.81649658]
 [ 1.         -0.40824829 -0.40824829]]


In [19]:
#计算方阵行列式
print(np.linalg.det(A))

1.9999999999999998


## 第四章：统计分析
### 4-1 简单数据统计

In [ ]:
np.amin(arr,0) #按列统计最小值，amax为最大值

# numpy.ptp() 函数计算数组中元素最大值与最小值的差（最大值 - 最小值）
np.ptp(arr,1) #按行求极差



axis: 可选参数，用于指定在哪个轴上计算最小值。如果不提供此参数，则返回整个数组的最小值。可以是一个整数表示轴的索引，也可以是一个元组表示多个轴。

<img height="500" src="https://lin01-image-1373317342.cos.ap-beijing.myqcloud.com/d30eeddc2d440fb917c47c642f126060.jpg?imageSlim" width="300"/>

In [ ]:
# percentile() 函数 求p百分位，若n*p为整数则取平均数，若有余数则下一位
a = np.array([[10, 7, 4],
              [3, 2, 1]])
print ('我们的数组是：')
print (a)

print ('调用 percentile() 函数：')
# 50% 的分位数，就是 a 里排序之后的中位数
print (np.percentile(a, 50))

# axis 为 0，在纵列上求
print (np.percentile(a, 50, axis=0))

# axis 为 1，在横行上求
print (np.percentile(a, 50, axis=1))

# 保持维度不变
print (np.percentile(a, 50, axis=1, keepdims=True))

In [ ]:
# 求中位数
#numpy.median() 函数用于计算数组 a 中元素的中位数
a = np.array([[10, 9, 4],
              [3, 4, 1]])
b = np.array([[10, 9,6, 4],
              [3, 4, 2,1]])
print(np.median(a,1))
print(np.median(b,1))

In [ ]:
# 求平均数
# numpy.mean() 函数返回数组中元素的算术平均值，如果提供了轴，则沿其计算。
import numpy as np
a = np.array([[10, 9, 4],
              [3, 4, 1]])
print(np.mean(a,1)) # 按行求平均数

[7.66666667 2.66666667]


In [ ]:
# 加权平均
a = np.array([[10, 9, 4],
              [3, 4, 1]])
wts = np.array([4,3,2])
print (np.average(a,1,weights = wts)) # 按行求加权平均

In [ ]:
# 标准差
## 公式 std = sqrt(mean((x - x.mean())**2))

print (np.std([1,2,3,4]))

# 方差=标准差的平方

print (np.var([1,2,3,4]))

### 4-2 排序
![](https://lin01-image-1373317342.cos.ap-beijing.myqcloud.com/20260112234440733.png?imageSlim)

In [7]:
# sort

a = np.array([[3,7],
              [9,1]])

print ('在列上排序：')
print (np.sort(a, axis =  0,kind='quicksort'))
print ('\n')


# 在 sort 函数中排序字段
dt = np.dtype([('name',  'S10'),('age',  int)])
b = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)
print ('按 name 排序：')
print (np.sort(b, order =  'name'))
print ('\n')

print ('全部打乱再排序：')
a1=a.reshape(-1)
print('b',a1)
print ('全部打乱再排序：')
print(np.sort(a1))

在列上排序：
[[3 1]
 [9 7]]


按 name 排序：
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


全部打乱再排序：
b [3 7 9 1]
全部打乱再排序：
[1 3 7 9]
